apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: readinglist-app
  namespace: argocd
spec:
  project: readinglist-proj
  source:
    repoURL: https://github.com/carlosrojasmatas/readinglist-ops.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: readinglist-dev
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true